In [1]:
import pandas as pd
import numpy as np

In [27]:
imdb=pd.read_csv('IMDB Movies Data - movie_metadata.csv')

In [28]:
imdb

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [29]:
imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5029 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [32]:
imdb.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      14
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [33]:
imdb['profit']=imdb['gross']-imdb['budget']

In [34]:
imdb['roi']=(imdb['gross']-imdb['budget'])/imdb['budget']

In [35]:
imdb[['gross','budget','profit','roi']].head()

         gross       budget       profit       roi
0  760505847.0  237000000.0  523505847.0  2.208885
1  309404152.0  300000000.0    9404152.0  0.031347
2  200074175.0  245000000.0  -44925825.0 -0.183371
3  448130642.0  250000000.0  198130642.0  0.792523
4          NaN          NaN          NaN       NaN

# 1. Which movie made the highest profit? Who were its producer and director? Identify the actors in that film.

In [52]:
Highest_profit=imdb.loc[imdb['profit'].idxmax()]
director=Highest_profit['director_name']
profit=Highest_profit['profit']
actors=Highest_profit['actor_1_name'],Highest_profit['actor_2_name'],Highest_profit['actor_3_name']
movie_name=Highest_profit['movie_title']
print(f'The Highest Profit is {profit} \nThe movie which made this profit was {movie_name}\nwhich is directed by {director}\nThe cast was {actors}')

The Highest Profit is 523505847.0
The movie which made this profit was Avatar
which is directed by James Cameron
The cast was ('CCH Pounder', 'Joel David Moore', 'Wes Studi')

# 2. This data has information about movies made in different languages. Which language has the highest average ROI (return on investment)?

In [58]:
lang_roi= imdb.groupby('language')['roi'].mean()
highest_avg_roi_language=lang_roi.idxmax()
highest_avg_roi_value=lang_roi.max()
print(f'The Highest Average Language Roi is {highest_avg_roi_language}\nThe Average is {highest_avg_roi_value}')

The Highest Average Language Roi is Persian
The Average is 27.90536874074074

# 3. Find out the unique genres of movies in this dataset.

In [68]:
a=set(imdb['genres'].unique())

In [71]:
unique_genres=set(genre for sublist in df['genres'].str.split('|').dropna() for genre in sublist)
print(unique_genres)

{'Action', 'Game-Show', 'Thriller', 'Biography', 'Adventure', 'Comedy', 'Drama', 'Fantasy', 'Family', 'Romance', 'Sport', 'News', 'Sci-Fi', 'Animation', 'Mystery', 'Horror', 'Music', 'War', 'Reality-TV', 'Musical', 'Western', 'Crime', 'Film-Noir', 'History', 'Documentary', 'Short'}

# 4. Make a table of all the producers and directors of each movie. Find the top 3 producers who have produced movies with the highest average RoI?

In [ ]:
table=imdb[['director_name','movie_title']]

# 5. Which actor has acted in the most number of movies? Deep dive into the movies, genres and profits corresponding to this actor.

In [78]:
actors = pd.concat([df['actor_1_name'], df['actor_2_name']])
actor_counts = actors.value_counts()
most_frequent_actor = actor_counts.idxmax()
movies_with_actor = imdb[(imdb['actor_1_name']==most_frequent_actor) | (imdb['actor_2_name']==most_frequent_actor)]
actor_details = {'actor': most_frequent_actor,'movie_count': actor_counts.max(),'movies': movies_with_actor[['movie_title', 'genres', 'profit']]}
actor_details

{'actor': 'Robert De Niro',
 'movie_count': 54,
 'movies':                                 movie_title  \
 293                         Little Fockers
 518   The Adventures of Rocky & Bullwinkle
 541                             Shark Tale
 619                           Killer Elite
 632                              The Score
 710                       Meet the Fockers
 761                                    Joy
 783                           Analyze That
 784                         Righteous Kill
 838                       Meet the Parents
 868                                  Ronin
 879                                The Fan
 920                                 Casino
 1140                              Sleepers
 1168                            15 Minutes
 1209                            The Intern
 1281                          Mean Streets
 1285                       City by the Sea
 1337                          Grudge Match
 1411                             Cape Fear
 1463                                 Heist
 1548                          Men of Honor
 1550                       The Big Wedding
 1605                          Analyze This
 1655                          Midnight Run
 1704                               Godsend
 1714           Once Upon a Time in America
 1764                            Last Vegas
 1827                              Flawless
 1829                    What Just Happened
 1854                        New Year's Eve
 1884                      The Untouchables
 1901                         Hide and Seek
 1903                            Goodfellas
 2045            The Bridge of San Luis Rey
 2067                         Marvin's Room
 2124                                 Stone
 2137               Silver Linings Playbook
 2290                       We're No Angels
 2294                      Everybody's Fine
 2351                        Hands of Stone
 2425                           Raging Bull
 2474                            Red Lights
 2629                       The Deer Hunter
 2630                           Wag the Dog
 2636                              Cop Land
 2700                                Brazil
 2794                    New York, New York
 2837                The Godfather: Part II
 2911                               Machete
 2930                          Jackie Brown
 3025                         Dirty Grandpa
 3317                                 Heist
 4535                           Taxi Driver

                                          genres       profit
 293                              Comedy|Romance   48383780.0
 518   Adventure|Animation|Comedy|Family|Fantasy  -49999390.0
 541           Adventure|Animation|Comedy|Family   85762022.0
 619                       Action|Crime|Thriller   -9906393.0
 632                        Crime|Drama|Thriller    3069884.0
 710                              Comedy|Romance  199167575.0
 761                      Biography|Comedy|Drama   -3556518.0
 783                                Comedy|Crime  -27877751.0
 784         Action|Crime|Drama|Mystery|Thriller  -19923562.0
 838                                      Comedy  111225040.0
 868             Action|Adventure|Crime|Thriller  -13390407.0
 879                 Action|Drama|Sport|Thriller  -36426209.0
 920                       Biography|Crime|Drama   -9561700.0
 1140                       Crime|Drama|Thriller    9300852.0
 1168                Action|Crime|Drama|Thriller  -17624564.0
 1209                               Comedy|Drama   40274748.0
 1281               Crime|Drama|Romance|Thriller    -467355.0
 1285               Crime|Drama|Mystery|Thriller  -37566085.0
 1337                               Comedy|Sport  -10197239.0
 1411                             Crime|Thriller   44100000.0
 1463                      Action|Crime|Thriller          NaN
 1548                            Biography|Drama   16814909.0
 1550                                     Comedy  -13215568.0
 1605                               Comedy|Crime   76694016.0
 1655               Action|Comedy|Crime|Thriller    8413606.0
 1704               Drama|Horror|Sci-Fi|Thriller  -10665355.0
 1714                                Crime|Drama  -24700000.0
 1764                             Comedy|Romance   35910583.0
 1827                         Comedy|Crime|Drama  -10514515.0
 1829                               Comedy|Drama  -23910635.0
 1854                             Comedy|Romance   -1459475.0
 1884                       Crime|Drama|Thriller   51270454.0
 1901              Drama|Horror|Mystery|Thriller   21097664.0
 1903                      Biography|Crime|Drama   21836394.0
 2045                              Drama|Romance  -23957120.0
 2067                                      Drama  -10217492.0
 2124                             Drama|Thriller  -20203976.0
 2137                       Comedy|Drama|Romance  111088910.0
 2290                               Comedy|Crime   -9444652.0
 2294                            Adventure|Drama  -12144354.0
 2351               Action|Biography|Drama|Sport          NaN
 2425                      Biography|Drama|Sport  -17954750.0
 2474              Drama|Horror|Mystery|Thriller          NaN
 2629                                  Drama|War          NaN
 2630                               Comedy|Drama   28022524.0
 2636                       Crime|Drama|Thriller   34886089.0
 2700                               Drama|Sci-Fi   -5071000.0
 2794                Drama|Music|Musical|Romance          NaN
 2837                                Crime|Drama   44300000.0
 2911                      Action|Crime|Thriller   16089953.0
 2930                             Crime|Thriller   27647595.0
 3025                                     Comedy   24037564.0
 3317                      Action|Crime|Thriller          NaN
 4535                                Crime|Drama          NaN  }